### PR TITLE
Change license to MIT

### PR DESCRIPTION
**Pull request by sGerli**
Hi contributors, as some of you may be aware of we originally chose a license without even knowing it's implications. Today as a petition from @Katharine we are starting this request to change this projects license to a MIT license, this with the purpose of getting more developers in that may be scared by the current license. In order to change this license we need your approval so if you've contributed code to this project please comment in here saying "I approve".

Approved:

- [x] @azertyfun
- [x] @phpeter
- [x] @frostyfrog
- [x] @modrzew 
- [x] @HenryDelMal
- [x] @j2ko

### CODE REVIEW

**Comment by Avamander** [comment]
> getting more developers in that may be scared by the current license

So the reason to change the licence is just to hypothetically attract more developers? Why would a single developer ever be "scared" by GPL?

**Comment by Katharine** [comment]
Because their employer takes issue with it.

**Comment by jwise** [comment]
No employee of Google can read or contribute to an AGPL project: https://opensource.google.com/docs/patching/#forbidden

**Comment by Avamander** [comment]
Are there any Google or any other developers that will pledge to contribute given this project conforms to that company's requirements? Asking this simply because I like my user freedoms valued.

**Comment by ishotjr** [comment]
@sGerli @Katharine thanks so much for bringing this up! :bowtie: :mag_right: :scroll:

**Comment by HenryDelMal** [comment]
I'm not really sure about this as MIT License is "too much unrestricted" compared to (L)GPL, but as it would allow more developers and more (privative) products working with this project, I think it would be fine, although I'd like to see more feedback from other contributors. (Anyway, my contributions were minor, so I think the opinion of @azertyfun @phpeter and @modrzew are decisive)

I approve.

**Review by azertyfun — APPROVED** [review]
I approve.

**Comment by phpeter** [comment]
I approve.

**Review by phpeter — APPROVED** [review]

**Comment by j2ko** [comment]
I approve

**Comment by TheTechmage** [comment]
Sorry for the late comment on this. I had merely seen #123 and I hadn't seen this issue in my emails before today. I prefer having at least (L)GPL because changes to the core code base should be contributed back, but I'm perfectly fine with moving the license to MIT as well.

**Review by modrzew — APPROVED** [review]
Sorry for the delay! :+1: from me as well.

**Pull request merged**
